@host = http://localhost:8080
# @host = https://jar-service.herokuapp.com

###
GET {{host}}/jar/resetall

###
GET {{host}}/jar/reset/NEQL3eTEIk

###
GET {{host}}/jar/all/NEQL3eTEIk

###
GET {{host}}/jar/card/NEQL3eTEIk

###
POST {{host}}/jar
Content-Type: application/json

{
   "jar": {
      "title": "Test Jar",
      "cardsPerDay": 1,
      "recipientEmail": "kondzir@gmail.com",
      "cards": [
         {
            "text": "U're looking good today!"
         },
         {
            "text": "Smile up!"
         },
         {
            "text": "H!"
         }
      ]
   }
}
