@host = http://localhost:8080

###
GET {{host}}/jar/all/ynAfTDxuNK

###
POST {{host}}/jar
Content-Type: application/json

{
   "jar": {
      "title": "Test Jar",
      "timesPerDay": 1,
      "recipientEmail": "aaa@a.com",
      "cards": [
         {
            "text": "U're looking good today!"
         },
         {
            "text": "Smile up!"
         },
         {
            "text": "H!"
         }
      ]
   }
}
